logging:
  file:
    path: log
spring:
  datasource:
    url: jdbc:mysql://localhost/eclipse?serverTimezone=UTC
    username: root
    password: root
eclipse:
  discord:
    token:
    debug:
      guild: